### ISSUE TITLE
Ileum CD Fibroblasts vs CD Control Fibroblasts

### ISSUE THREAD

**Issue by jaljabban** [Humanitas-Danese-s-omics/ibd-meta-analysis-data#4]
Hello,

I came across this excellent website. I see that there are comparisons between colonic fibroblasts in CD and in control samples. I did not see the same option for ileum-derived fibroblasts in CD. Is that data available and if not can it possible be added? Thank you!

Best,
-JJ

**Comment by luigilamparelli** [comment]
Hi JJ,

this analysis has been completed and the data available is intended to remain as it is. If the group will perform a new analysis (with new data), will be published in a new platform.

Thanks for writing,
Luigi
